%
% This file is part of AtomVM.
%
% Copyright 2026 Paul Guyot <pguyot@kallisys.net>
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
%
% SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
%

%%-----------------------------------------------------------------------------
%% @doc An implementation of a subset of the Erlang/OTP erts_internal interface.
%%
%% These functions are not meant to be called directly.  They are helpers,
%% called from code generated by the compiler.  In particular `mc_iterator/1'
%% and `mc_refill/1' implement map comprehensions (`#{K => V || K := V <- M}'),
%% introduced in OTP 26.  The generated bytecode is identical from OTP 26 to at
%% least OTP 29.
%% @end
%%-----------------------------------------------------------------------------
-module(erts_internal).

-export([mc_iterator/1, mc_refill/1]).

%% Associations handed to the comprehension per call. Bounded because the chain
%% is built by non-tail recursion and is materialised eagerly.
-define(MC_CHUNK, 32).

%%-----------------------------------------------------------------------------
%% @param   MapOrIter   a map or a map iterator to iterate over
%% @returns the first association as `{Key, Value, NextIterator}', `none' if the
%%          map or iterator is empty, or `[]' if the argument is not a valid
%%          generator
%% @doc     Start iterating over a map comprehension generator.
%%
%% This function is a helper called from compiler generated code for map
%% comprehensions.  It must be kept compatible as long as code calling this
%% helper can still be loaded.
%% @end
%%-----------------------------------------------------------------------------
-spec mc_iterator(MapOrIter) -> Iter when
    MapOrIter :: map() | maps:iterator(),
    Iter :: {term(), term(), maps:iterator()} | none | [].
mc_iterator(Map) when is_map(Map) ->
    mc_chunk(maps:next([0 | Map]), ?MC_CHUNK);
mc_iterator([Path | Map]) ->
    %% This is probably an iterator.
    try maps:next([Path | Map]) of
        Iter -> mc_chunk(Iter, ?MC_CHUNK)
    catch
        error:badarg -> []
    end;
mc_iterator(MapIter) ->
    %% Possible "used" iterator. Must validate it.
    case is_map_iter(MapIter) of
        true -> MapIter;
        false -> []
    end.

is_map_iter({_, _, Iter}) ->
    is_map_iter(Iter);
is_map_iter(Iter) ->
    case Iter of
        [Path | Map] ->
            try maps:next([Path | Map]) of
                _ -> true
            catch
                error:badarg -> false
            end;
        none ->
            true;
        _ ->
            false
    end.

%%-----------------------------------------------------------------------------
%% @param   IterMap     a map iterator to refill
%% @returns the next association as `{Key, Value, NextIterator}' or `none'
%% @doc     Advance a map comprehension iterator.
%%
%% This function is a helper called from compiler generated code for map
%% comprehensions.  It must be kept compatible as long as code calling this
%% helper can still be loaded.
%% @end
%%-----------------------------------------------------------------------------
-spec mc_refill(IterMap) -> Iter when
    IterMap :: nonempty_improper_list(non_neg_integer() | list(), map()),
    Iter :: {term(), term(), maps:iterator()} | none.
mc_refill([Path | Map]) ->
    mc_chunk(maps:next([Path | Map]), ?MC_CHUNK).

%% Chain up to `N' associations into `{K1, V1, {K2, V2, ..., Iter}}', the shape
%% the compiler-generated loop already understands: it consumes a tuple
%% directly and only calls back here when it reaches the plain iterator at the
%% end of the chain. Returning one association at a time instead costs that
%% loop an extra call plus a self tail call for every element of the map.
mc_chunk(none, _N) ->
    none;
mc_chunk(Iter, 1) ->
    Iter;
mc_chunk({Key, Value, Iter}, N) ->
    {Key, Value, mc_chunk(maps:next(Iter), N - 1)}.
