#
#  Copyright 2022 Paul Guyot <pguyot@kallisys.net>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: Run tests with BEAM

on:
  push:
    paths-ignore:
      - 'src/platforms/esp32/**'
      - 'src/platforms/stm32/**'
      - 'doc/**'
      - 'LICENSES/**'
  pull_request:
    paths-ignore:
      - 'src/platforms/esp32/**'
      - 'src/platforms/stm32/**'
      - 'doc/**'
      - 'LICENSES/**'

jobs:
  run-tests:
    runs-on: "ubuntu-22.04"
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - checkout: "OTP-25.0"
        - checkout: "OTP-25.3.2.5"
        - checkout: "OTP-26.0"
        - checkout: "maint"
        - checkout: "OTP-26.0-rc1"
        - checkout: 104dc8355dd52651cf4eed0b32022309a34e649d
        - checkout: 197801a62c1782bf18a294b21a709f1cf2ca2633
        - checkout: fe65f7a032627c476c55c528c192cdcddbb3240f

    steps:
    # Setup
    - name: "Checkout repo"
      uses: actions/checkout@v3

    - name: "Fetch source using erlang/otp git repo"
      run: |
        set -eux
        git clone https://github.com/erlang/otp.git
        cd otp
        git checkout ${{ matrix.checkout }}

    - name: "Build from source and install with another prefix"
      run: |
        set -eux
        cd otp
        export PIE_CFLAGS=-fpie
        export PIE_LDFLAGS=-pie
        ./configure --with-ssl --enable-dirty-schedulers
        make -j
        make -j release
        cd release/x86_64-pc-linux-gnu
        ./Install -minimal $PWD

    - name: "Test compile module and test it"
      timeout-minutes: 10
      run: |
        set -eux
        test -e otp/bin && export PATH=${PWD}/otp/bin:${PATH}
        test -e /opt/hostedtoolcache/otp-source/bin && export PATH=/opt/hostedtoolcache/otp-source/bin:${PATH}
        test -e otp/release/x86_64-pc-linux-gnu/bin && export PATH=${PWD}/otp/release/x86_64-pc-linux-gnu/bin:${PATH}
        which erl
        which erlc
        erl=`which erl`
        installed_path=`dirname $erl`
        installed_path=`dirname $installed_path`
        find $installed_path -name beam.smp -exec md5sum \{\} \;
        erl -version
        erl -eval 'io:format("~s", [erlang:system_info(system_version)]), init:stop().' -noshell
        erlc tests/erlang_tests/test_gc.erl
        erl -pa . -eval 'erlang:process_flag(trap_exit, false), test_gc:start(), erlang:halt(0).' -noshell
        erl -pa . -eval 'R = test_gc:start(), S = 0, erlang:halt(S).' -noshell
        erl -pa . -eval 'R = test_gc:start(), S = if R =:= 0 -> 0; true -> 1 end, erlang:halt(S).' -noshell
        erl -pa . -eval 'R = test_gc:start(), S = if R =:= 0 -> 0; true -> io:format("Expected ~B, got ~p~n", [0, R]), 1 end, erlang:halt(S).' -noshell
        erl -pa . -eval 'erlang:process_flag(trap_exit, false), R = test_gc:start(), S = if R =:= 0 -> 0; true -> io:format("Expected ~B, got ~p~n", [0, R]), 1 end, erlang:halt(S).' -noshell
