#
#  Copyright 2022 Paul Guyot <pguyot@kallisys.net>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: Run tests with BEAM

on:
  push:
    paths-ignore:
      - 'src/platforms/esp32/**'
      - 'src/platforms/stm32/**'
      - 'doc/**'
      - 'LICENSES/**'
  pull_request:
    paths-ignore:
      - 'src/platforms/esp32/**'
      - 'src/platforms/stm32/**'
      - 'doc/**'
      - 'LICENSES/**'

jobs:
  run-tests:
    runs-on: "ubuntu-22.04"
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        install_opt: ["-minimal", "-sasl", "make_install_prefix", "make_install"]
        checkout:
        - "OTP-25.0"
        - "OTP-26.0-rc1"
        # Wed Feb 15 02:44:39 2023 -0500
        - d47fc50422d050612e447d4439b27a01c29f46ce
        # Wed Feb 15 10:09:32 2023 +0100
        - 127026003180a834e9fa5d5919c824a184faeb92
        - dc132c20447a4780fc9dc7f449b00523876e0f97
        - 2b397d7e5580480dc32fa9751db95f4b89ff029e
    steps:
    # Setup
    - name: "Checkout repo"
      uses: actions/checkout@v3

    - name: "Fetch source using erlang/otp git repo"
      run: |
        set -eux
        git clone https://github.com/erlang/otp.git
        cd otp
        git checkout ${{ matrix.checkout }}

    - name: "Build from source and install"
      run: |
        set -eux
        cd otp
        export PIE_CFLAGS=-fpie
        export PIE_LDFLAGS=-pie
        if [ "${{ matrix.install_opt}}" = "make_install_prefix" ]; then
            ./configure --with-ssl --enable-dirty-schedulers --prefix=../otp_install
            mkdir ../otp_install
            make -j
            make -j install
        elif [ "${{ matrix.install_opt}}" = "make_install" ]; then
            ./configure --with-ssl --enable-dirty-schedulers
            make -j
            sudo make -j install
        else
            ./configure --with-ssl --enable-dirty-schedulers
            make -j
            make -j release
            cd release/x86_64-pc-linux-gnu
            ./Install ${{ matrix.install_opt}} $PWD
            test -e releases/26 && grep erts-14.0.2 releases/26/installed_application_versions && (
            cat releases/*/installed_application_versions
            cat << EOF > installed_application_versions.diff
        --- /opt/erlang/erlang-master-minimal/releases/26/installed_application_versions	2023-08-29 07:56:36
        +++ /opt/erlang/erlang-master/lib/erlang/releases/26/installed_application_versions	2023-08-29 07:58:02
        @@ -1,3 +1,4 @@
        +erts-14.0.2
         stdlib-5.0.2
         sasl-4.2.1
         kernel-9.0.2
        @@ -34,4 +35,3 @@
         dialyzer-5.1
         ftp-1.2
         tftp-1.1
        -erts-14.0.2
        EOF
            patch -p3 < installed_application_versions.diff
            )
        fi

    - name: "Test compile module and test it"
      timeout-minutes: 10
      run: |
        set -eux
        test -e otp_install/bin && export PATH=${PWD}/otp_install/bin:${PATH}
        test -e otp/release/x86_64-pc-linux-gnu/bin && export PATH=${PWD}/otp/release/x86_64-pc-linux-gnu/bin:${PATH}
        which erl
        which erlc
        erl=`which erl`
        installed_path=`dirname $erl`
        installed_path=`dirname $installed_path`
        find $installed_path -name beam.smp -exec md5sum \{\} \;
        erl -version
        erl -eval 'io:format("~s", [erlang:system_info(system_version)]), init:stop().' -noshell
        erlc tests/erlang_tests/test_gc.erl
        erl -pa . -eval 'erlang:process_flag(trap_exit, false), test_gc:start(), erlang:halt(0).' -noshell
        erl -pa . -eval 'R = test_gc:start(), S = 0, erlang:halt(S).' -noshell
        erl -pa . -eval 'R = test_gc:start(), S = if R =:= 0 -> 0; true -> 1 end, erlang:halt(S).' -noshell
        erl -pa . -eval 'R = test_gc:start(), S = if R =:= 0 -> 0; true -> io:format("Expected ~B, got ~p~n", [0, R]), 1 end, erlang:halt(S).' -noshell
        erl -pa . -eval 'erlang:process_flag(trap_exit, false), R = test_gc:start(), S = if R =:= 0 -> 0; true -> io:format("Expected ~B, got ~p~n", [0, R]), 1 end, erlang:halt(S).' -noshell
